package com.rnllama;

import androidx.annotation.NonNull;

import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactContextBaseJavaModule;

/**
 * Compatibility stub for Old Architecture (non-TurboModule).
 * Normally generated by React Native codegen when New Architecture is enabled.
 */
public abstract class NativeRNLlamaSpec extends ReactContextBaseJavaModule implements NativeModule {
  public NativeRNLlamaSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @NonNull
  @Override
  public abstract String getName();

  public abstract void install(Promise promise);
}
